language: node_js

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js: "6"

env:
  - CC=gcc-4.8 CXX=g++-4.8

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=$PATH:$HOME/.cargo/bin

script: npm run ci

git:
  depth: 10

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
