#!/usr/bin/env sh

echo "Downloading node v0.12.0..."
curl -s -O http://nodejs.org/dist/v0.12.0/node-v0.12.0-darwin-x64.tar.gz
tar -zxf node-v0.12.0-darwin-x64.tar.gz
export PATH=$PWD/node-v0.12.0-darwin-x64/bin:$PATH

npm install
npm test
